
before_script:
  - make demo
  - make data
  - make germline
  - make -C browser sha1
  - cp -p doc/analysis-example.vidjil browser/

stages:
  - test_tools
  - test_quality
  - test_unit
  - deploy_review
  - test_germlines
  - test_functional
  - test_shouldvdj
  - test_functional_external
  - coverage
  - prepare_release
  - tgz_release
  - valgrind_unit
  - valgrind_functional
  - multiple_tests
  - benchmark
  - publish_release
  - deploy_prod

# Anchors

.coverage_dependency:
  artifacts: &lcov_artifact
    paths:
      - algo/lcov_test_*.filtered
    expire_in: 1 week

# Tools

test_tools:
  stage: test_tools
  script: make -C tools/tests


# Germlines

test_germlines:
  stage: test_germlines
  script:
    - make -C germline get-all-data
    - make -C germline tests
  only:
    - /^feature-.*g.*\/.*$/
    - schedules

# Doc

include:
  - local: '/doc/.gitlab-ci.yml'

# Algorithm

test_algo_unit:
  stage: test_unit
  script: make -C algo unit_coverage
  artifacts:
    <<: *lcov_artifact
  only:
    - /^feature-.*a.*\/.*$/
    - schedules

test_algo_should:
  stage: test_functional
  script: make -C algo should_coverage
  artifacts:
    <<: *lcov_artifact
    reports:
      junit: algo/tests/should.xml
  only:
    - /^feature-.*a.*\/.*$/
    - schedules

test_algo_shouldvdj:
  stage: test_shouldvdj
  script: make -C algo shouldvdj_coverage
  artifacts:
    <<: *lcov_artifact
  only:
    - /^feature-.*a.*\/.*$/
    - schedules
  
algo_coverage:
  stage: coverage
  coverage: /^\s*lines\.*:\s+([0-9.]+\%)/
  script:
    - make -C algo lcov_reports
    - mv algo/reports/ coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - /^feature-.*a.*\/.*$/
    - schedules

algo_valgrind_unit:
  stage: valgrind_unit
  script: make -C algo valgrind_unit
  only:
    - /^feature-.*a.*\/.*$/
    - schedules
  tags:
    - valgrind

.snip_valgrind_functional: &valgrind_functional
  stage: valgrind_functional
  script: make -C algo valgrind_should
  tags:
    - valgrind

algo_valgrind_functional:
  <<: *valgrind_functional
  when: manual
  only:
    - /^feature-.*a.*\/.*$/
    - schedules

release_valgrind_functional:
  <<: *valgrind_functional
  only:
    - /^feature-.*a.*\/release$/

prepare_release:
  stage: prepare_release
  script: make -C algo release RELEASE_TAG='rc'
  when: manual
  only:
    - /^feature-.*a.*\/.*$/

tgz_release:
  stage: tgz_release
  script: make -C algo release RELEASE_TAG=`cat algo/release`
  only:
    - /^feature-.*a.*\/release$/
  artifacts:
    paths:
    - algo/releases/vidjil-algo-`cat algo/release`.tar.gz
    - algo/releases/vidjil-algo-`cat algo/release`/vidjil-algo-`cat algo/release`_`uname -m`
    expire_in: 10 years
  allow_failure: false
  tags:
    - ubuntu-16.04-amd64

copy_release:
  stage: publish_release
  script:
    - |
      for repo in $ALGO_REPOSITORIES; do
        echo "Copying release to $repo"
        scp algo/releases/vidjil-algo*.tar.gz algo/releases/vidjil-algo*/vidjil-algo-*_* $repo
      done
      release_name=$(cat algo/release)
      ssh $VIDJIL_WWW "cd /var/www/html/releases; ln -sf vidjil-algo-${release_name}.tar.gz vidjil-latest.tgz; ln -sf vidjil-algo-${release_name}_x86_64 vidjil-latest_x86_64"
      ssh $VIDJIL_BONSAI "cd /bio1/www/html/vidjil; scp vidjil-algo-${release_name}* $VIDJIL_BONSAI_PROD:/bio1/www/html/vidjil"
  when: manual
  only:
    - /^feature-.*a.*\/release$/

deploy_release_prod:
  stage: deploy_prod
  when: manual
  only:
    - /^feature-.*a.*\/release$/
  script:
    - |
      release_name=$(cat algo/release)
      ssh $DEPLOY_SERVER "cd releases/vidjil;\
          tar xvzf vidjil-algo-${release_name}.tar.gz;\
          make -C vidjil-algo-${release_name};\
          ln -sfT vidjil-algo-${release_name} next"

.testing-compilers:
  stage: multiple_tests
  tags:
    - cidocker
  before_script:
    - apt-get update
    - apt-get install -y time valgrind python3 wget tar
  script:
    - $CXX --version
    - make demo data germline
    - make -C algo clean
    - make -C algo CXX=$CXX CC=$CC unit
    - make -C algo CXX=$CXX CC=$CC should
    - make -C algo CXX=$CXX CC=$CC valgrind_unit

.testing-gcc:
  extends: .testing-compilers
  variables:
    CXX: g++
    CC: gcc

.installing-compiler:
  before_script:
    - apt-get update
    - apt-get install -y time valgrind python3 $COMPILER_PKG-$VERSION zlib1g-dev make wget tar python2.7
    - ln -sf /usr/bin/python2.7 /usr/bin/python
    - export CXX=${COMPILER_CPP}-$VERSION
    - export CC=${COMPILER_C}-$VERSION
  

.testing-clang:
  variables:
    COMPILER_PKG: "clang"
    COMPILER_CPP: "clang++"
    COMPILER_C: "clang"
    VERSION: $CLANG_VERSION
  extends:
    - .testing-compilers
    - .installing-compiler      # Overrides the before_script to install the compiler

.installing-testing-gcc:
  variables:
    COMPILER_PKG: "g++"
    COMPILER_CPP: "g++"
    COMPILER_C: "gcc"
    VERSION: $GCC_VERSION
  extends:
    - .testing-compilers
    - .installing-compiler
    
    
.testing_various_compilers_manual:
  when: manual
  only:
    - /^feature-.*a.*\/.*$/
    - schedules
    
.testing_various_compilers_release:
  only:
    - /^feature-.*a.*\/release$/

test_gcc48_manual:
  image: debian:8-slim
  variables:
    GCC_VERSION: "4.8"
  extends:
    - .installing-testing-gcc
    - .testing_various_compilers_manual
test_gcc48_release:
  image: debian:8-slim
  variables:
    GCC_VERSION: "4.8"
  extends:
    - .installing-testing-gcc
    - .testing_various_compilers_release
test_gcc5_manual:
  image: gcc:5.3
  extends:
    - .testing-gcc
    - .testing_various_compilers_manual
test_gcc5_release:
  image: gcc:5.3
  extends:
    - .testing-gcc
    - .testing_various_compilers_release
test_gcc6_manual:
  image: gcc:6.3
  extends:
    - .testing-gcc
    - .testing_various_compilers_manual
test_gcc6_release:
  image: gcc:6.3
  extends:
    - .testing-gcc
    - .testing_various_compilers_release
test_gcc7_manual:
  image: gcc:7.3
  extends:
    - .testing-gcc
    - .testing_various_compilers_manual
test_gcc7_release:
  image: gcc:7.3
  extends:
    - .testing-gcc
    - .testing_various_compilers_release
test_gcc8_manual:
  image: gcc:8
  extends:
    - .testing-gcc
    - .testing_various_compilers_manual
test_gcc8_release:
  image: gcc:8
  extends:
    - .testing-gcc
    - .testing_various_compilers_release
test_gcc9_manual:
  image: gcc:9
  extends:
    - .testing-gcc
    - .testing_various_compilers_manual
test_gcc9_release:
  image: gcc:9
  extends:
    - .testing-gcc
    - .testing_various_compilers_release
test_clang34_manual:
  image: debian:8-slim
  variables:
    CLANG_VERSION: "3.4"
  extends:
    - .testing-clang
    - .testing_various_compilers_manual
test_clang34_release:
  image: debian:8-slim
  variables:
    CLANG_VERSION: "3.4"
  extends:
    - .testing-clang
    - .testing_various_compilers_release
test_clang4_manual:
  image: debian:8-slim
  variables:
    CLANG_VERSION: "4.0"
  extends:
    - .testing-clang
    - .testing_various_compilers_manual
test_clang4_release:
  image: debian:8-slim
  variables:
    CLANG_VERSION: "4.0"
  extends:
    - .testing-clang
    - .testing_various_compilers_release
test_clang6_manual:
  image: debian:8-slim
  variables:
    CLANG_VERSION: "6.0"
  extends:
    - .testing-clang
    - .testing_various_compilers_manual
test_clang6_release:
  image: debian:8-slim
  variables:
    CLANG_VERSION: "6.0"
  extends:
    - .testing-clang
    - .testing_various_compilers_release
test_clang7_manual:
  image: debian:10-slim
  variables:
    CLANG_VERSION: "7"
  extends:
    - .testing-clang
    - .testing_various_compilers_manual
test_clang7_release:
  image: debian:10-slim
  variables:
    CLANG_VERSION: "7"
  extends:
    - .testing-clang
    - .testing_various_compilers_release




# Client

test_browser_unit:
  stage: test_unit
  script: make unit_browser
  artifacts:
    paths:
    - browser/
  only:
    - /^feature-.*c.*\/.*$/
    - /^hotfix-.*c.*\/.*$/
    - prod-client
    - dev
    - schedules
  tags:
    - web

.browser-functional:
  stage: test_functional
  retry: 2
  script:
    - make -C browser
    - source /etc/profile.d/rvm.sh
    - rvm use 2.6.1
    - HEADLESS=1 make -C browser/test functional
  artifacts:
    paths:
    - browser/
    reports:
      junit: browser/test/test/TEST-*.xml
  only:
    - /^feature-.*c.*\/.*$/
    - /^hotfix-.*c.*\/.*$/
    - prod-client
    - schedules
  tags:
    - web

.browser-functional-chrome:
  extends: .browser-functional
  variables:
    WATIR_CHROME: "1"

.browser-functional-external:
  stage: test_functional_external
  retry: 2
  script:
    - make -C browser
    - source /etc/profile.d/rvm.sh
    - rvm use 2.6.1
    - HEADLESS=1 make -C browser/test external
  artifacts:
    paths:
    - browser/
    reports:
      junit: browser/test/test/TEST-*.xml
  only:
    - /^feature-.*c.*\/.*$/
    - /^hotfix-.*c.*\/.*$/
    - prod-client
    - schedules
  tags:
    - web

.browser-functional-external-chrome:
  extends: .browser-functional-external
  variables:
    WATIR_CHROME: "1"
    
ff32-browser-functional:
  extends: .browser-functional
  variables:
    FIREFOX_VERSION: 32

ff45-browser-functional:
  extends: .browser-functional
  variables:
    FIREFOX_VERSION: 45

chrome-browser-functional:
  extends: .browser-functional-chrome
        
old-chrome-browser-functional:
  extends: .browser-functional-chrome
  tags:
    - legacy

ff32-browser-functional-external:
  extends: .browser-functional-external
  variables:
    FIREFOX_VERSION: 32

ff45-browser-functional-external:
  extends: .browser-functional-external
  variables:
    FIREFOX_VERSION: 45

chrome-browser-functional-external:
  extends: .browser-functional-external-chrome
    
old-chrome-browser-functional-external-chrome:
  extends: .browser-functional-external-chrome
  tags:
    - legacy

code_quality:
  stage: test_quality
  script: make -C browser quality
  only:
    - /^feature-.*c.*\/.*$/
    - /^hotfix-.*c.*\/.*$/
    - prod-client
    - dev
    - schedules
  tags:
    - web

# Server

test_server_unit:
    stage: test_unit
    script:
      - virtualenv $CI_BUILD_REF_SLUG
      - source $CI_BUILD_REF_SLUG/bin/activate
      - pip install -r requirements.txt
      - make -C server install_web2py_standalone
      - make -C server launch_fuse_server
      - make unit_server || (make -C server kill_fuse_server; deactivate; false)
      - make -C server kill_fuse_server
      - deactivate
    artifacts:
      reports:
        junit: server/web2py/test-reports/TEST*xml
    only:
      - /^feature-.*s.*\/.*$/
      - /^hotfix-.*s.*\/.*$/
      - prod-server
      - dev
      - schedules
    tags:
      - web

.test_server_functional:
  stage: test_functional
  script:
    - docker build --no-cache --build-arg git_branch=$CI_COMMIT_REF_NAME --build-arg build_env=TEST -t "vidjil/server:test" docker/vidjil-server
    - docker build --no-cache --build-arg git_branch=$CI_COMMIT_REF_NAME --build-arg build_env=TEST -t "vidjil/client:test" docker/vidjil-client
    - sed -i '/\/etc\/nginx\/ssl\:\/etc\/nginx\/ssl/d' ./docker/docker-compose.yml
    - sed -i 's/\:latest/\:test/g' ./docker/docker-compose.yml
    - cd docker/vidjil-server/conf/ && mv defs.py defs_https.py && mv defs_http.py defs.py && cd ../../..
    - make germline && cp browser/js/germline.js docker/vidjil-client/conf
    - cd docker && docker-compose up -d && cd ..
    - sed -i "s/^python\ \.\.\/\.\.\/\.\./docker\ exec\ docker_uwsgi_1\ python\ \/usr\/share\/vidjil\/server\/web2py/" server/web2py/applications/vidjil/tests/init_tests.sh
    - docker exec docker_uwsgi_1 sed -i "s/^\(FILE_SOURCE .*\)/FILE_SOURCE = '\/usr\/share\/vidjil\/demo'/" /usr/share/vidjil/server/web2py/applications/vidjil/modules/defs.py
    - docker exec docker_nginx_1 make -C /usr/share/vidjil browser
    - source /etc/profile.d/rvm.sh
    - rvm use 2.6.1
    - HEADLESS=1 make functional_server || (cd docker && docker-compose stop; docker stop $(docker ps -aq); docker rm $(docker ps -aq); docker rmi "vidjil/server:test" "vidjil/client:test"; false)
    - cd docker && docker-compose stop
    - docker stop $(docker ps -aq)
    - docker rm $(docker ps -aq)
    - docker rmi "vidjil/server:test" "vidjil/client:test" reporter:test
  artifacts:
    reports:
      junit: server/web2py/applications/vidjil/tests/test/TEST-*.xml
  only:
    - /^feature-.*s.*\/.*$/
    - /^hotfix-.*s.*\/.*$/
    - prod-server
    - dev
    - schedules
  tags:
    - x86_64
    - docker

ff32-server-functional:
  extends: .test_server_functional
  variables:
    FIREFOX_VERSION: 32

ff45-server-functional:
  extends: .test_server_functional
  variables:
    FIREFOX_VERSION: 45



# Benchmark

benchmark_algo:
  stage: benchmark
  script:
    - cd algo/tests ; python3 benchmark-releases.py -bic
  when: manual
  only:
    - /^feature-.*a.*\/.*$/
  tags:
    - several-compilers


# Deployment

deploy_review:
  stage: deploy_review
  script:
    - make -C browser icons
    - echo "$REVIEW_CONFIG_JS" > browser/js/conf.js
    - rsync -av --delete browser $REVIEW_SERVER:$REVIEW_SERVER_PATH$CI_BUILD_REF_SLUG
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.ci.vidjil.org/?data=analysis-example.vidjil
    on_stop: stop_deploy_review
  only:
    - /^feature-.*c.*\/.*$/
    - /^hotfix-.*c.*\/.*$/
  tags:
    - web

deploy_docker:
  stage: deploy_prod
  script:
    - export CUR_DATE=`date +%Y-%m-%d`
    - export TYPE=`echo $CI_COMMIT_REF_NAME | awk '{ gsub(/prod-/, "") }{ print $1 }'`
    - export SHA=`echo $CI_COMMIT_SHA | awk '{ print substr($0, 0, 8) }'`
    - export TAG="vidjil/$TYPE:$CUR_DATE-$SHA"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --no-cache --build-arg git_branch=$CI_COMMIT_REF_NAME --build-arg build_env=PRODUCTION -t $TAG docker/vidjil-$TYPE
    - docker push $TAG
    - docker tag $TAG "vidjil/$TYPE:latest"
    - docker push "vidjil/$TYPE:latest"
    - docker rmi $TAG "vidjil/$TYPE:latest"
  when: manual
  only:
    - prod-server
    - prod-client
  tags:
    - web
    - docker

deploy_prod:
  stage: deploy_prod
  script:
    - ssh $PROD_CLIENT_SERVER "
         cd $PROD_CLIENT_PATH;
         git fetch
         && git reset --hard origin/prod-client
         && make -C browser
         && make -C browser sha1
         && cp doc/analysis-example.vidjil browser/"
  environment:
    name: production
    url: http://$PROD_CLIENT_SERVER/?data=analysis-example.vidjil
  only:
    - prod-client
  tags:
    - web

deploy_germlines:
  stage: deploy_prod
  script:
    - make -C germline get-all-data
    - make -C germline js
    - date=$(date +%Y-%m-%d)
    - tar cvzf germline-$date.tar.gz germline/*/*.fa germline/IMGT_RELEASE browser/js/germline.js
    - scp germline-$date.tar.gz $VIDJIL_WWW:$REMOTE_GERMLINE_DIR
  only:
    - manual
    - /^feature-.*g.*\/.*$/
    


stop_deploy_review:
  stage: deploy_review
  variables:
    GIT_STRATEGY: none
  script:
    - ssh $REVIEW_SERVER "rm -rf $REVIEW_SERVER_PATH$CI_BUILD_REF_SLUG"
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  only:
    - /^feature-.*c.*\/.*$/
    - /^hotfix-.*c.*\/.*$/
  tags:
    - web
