site_name: Vidjil

docs_dir: doc

plugins: []

repo_url: https://gitlab.inria.fr/vidjil/vidjil
repo_name: gitlab

pages:
    - / : index.md
    - user manual: user.md
    - recombinations: locus.md
    - vidjil-algo: vidjil-algo.md
    - .vidjil format: vidjil-format.md
    - admin: admin.md
    - server: server.md
    - quality: quality.md
    - credits: credits.md

extra_css:
    - mkdocs-extra.css

