
build_doc:
  stage: tgz_release
  script:
    - make -C doc html
    - find site -name "*.html" -type f | xargs python tools/validate-links.py
  artifacts:
    paths:
      - site/
    expire_in: 1 month
  only:
    refs:
      - merge_requests
    changes:
      - doc/**/*
      - mkdocs.yml
  tags:
    - doc

deploy_doc:
  stage: deploy_prod
  script:
    - scp -r site/ $VIDJIL_WWW:doc/
  when: manual
  only:
    refs:
      - merge_requests
    changes:
      - doc/**/*
      - mkdocs.yml
